version: '3.8'

services:
  app:
    build: .
    image: encurta.me-app
    container_name: app-encurtame
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    networks:
      - encurta-network
    depends_on:
      - db
    restart: always

  db:
    image: mongo:latest
    container_name: mongodb-encurtame
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - encurta-network
    restart: always

networks:
  encurta-network:
    driver: bridge

volumes:
  mongo_data:
